# Question 1

In [2]:
import numpy as np
arr=np.arange(2,51,3)
print(arr)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2

In [4]:
list1=[]
list2=[]
for i in range(5):
    x=int(input('Enter the values for list1:'))
    list1.append(x)
for i in range(5):
    x=int(input('Enter the values for list2:'))
    list2.append(x)
arr1=np.array(list1)
arr2=np.array(list2)
arr=np.concatenate((arr1,arr2))
print('Array value for concatenated arr:',arr)
sortedArray=np.sort(arr)
print('Sorted array concatenated array:',sortedArray)


Enter the values for list1:2
Enter the values for list1:67
Enter the values for list1:54
Enter the values for list1:34
Enter the values for list1:78
Enter the values for list2:98
Enter the values for list2:45
Enter the values for list2:56
Enter the values for list2:90
Enter the values for list2:76
Array value for concatenated arr: [ 2 67 54 34 78 98 45 56 90 76]
Sorted array concatenated array: [ 2 34 45 54 56 67 76 78 90 98]


# Question 3

In [6]:
arr=np.array([[3,7,9],[5,8,3],[8,6,5]])
print('Dimensions in array:',arr.ndim)
print('Size of array:',arr.size)




Dimensions in array: 2
Size of array: 9
Shape of array: (3, 3)


# Question 4

In [7]:
arr=np.arange(10)
print('Shape of array:',arr.shape)
row_arr=arr[np.newaxis,:]
print('Shape of 2d array in row major:',row_arr.shape)
col_arr=arr[:,np.newaxis]
print('Shape of 2d array in column major:',col_arr.shape)


Shape of array: (10,)
Shape of 2d array in row major: (1, 10)
Shape of 2d array in column major: (10, 1)


In [8]:
arr=np.arange(10)
print('Shape of array:',arr.shape)
row_arr=np.expand_dims(arr,axis=0)
print('shape of 2d array in row major:',row_arr.shape)
col_arr=np.expand_dims(arr,axis=1)
print('Shape of 2d array in column major:',col_arr.shape)

Shape of array: (10,)
shape of 2d array in row major: (1, 10)
Shape of 2d array in column major: (10, 1)


# Question 5 

In [9]:
import numpy as np

arr_1=np.square([1,2,3,4,5])
arr_2=np.square([6,7,8,9,10])

print('Horizontal Append:',np.hstack((arr_1,arr_2)))
print('Vertical Append:',np.vstack((arr_1,arr_2)))


Horizontal Append: [  1   4   9  16  25  36  49  64  81 100]
Vertical Append: [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# Question 6

In [10]:
import numpy as np

arr_1=np.array([1,4,9,16,25,1,4,2,3,2,5,6,5,7,8,10])
unique,counts=np.unique(arr_1,return_counts=True)

arr=np.asarray((unique,counts)).T
print(arr)

[[ 1  2]
 [ 2  2]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  1]
 [10  1]
 [16  1]
 [25  1]]
